/* eslint-disable */
// This file is auto-generated by scripts/generate-icons.mjs.
// Do not edit it manually.

import { useId, type ReactElement, type SVGProps } from "react";

export const ICON_NAMES = [
  "analysis",
  "chart",
  "clock",
  "company",
  "employees",
  "entry",
  "flag",
  "history",
  "lock",
  "mail",
  "out",
  "plus",
  "registerIn",
  "registerOut",
  "search",
  "timer",
  "union",
  "update"
] as const;

export type IconName = (typeof ICON_NAMES)[number];
export type IconComponent = (props: SVGProps<SVGSVGElement>) => ReactElement;

function createIcon(
  baseProps: SVGProps<SVGSVGElement>,
  rawInnerHtml: string
): IconComponent {
  return function GeneratedIcon(props) {
    const scopeId = useId().replace(/:/g, "_");
    const scopedInnerHtml = scopeSvgIds(rawInnerHtml, scopeId);

    return (
      <svg
        {...baseProps}
        {...props}
        dangerouslySetInnerHTML={{ __html: scopedInnerHtml }}
      />
    );
  };
}

function scopeSvgIds(innerHtml: string, scopeId: string) {
  return innerHtml
    .replace(/id="([^"]+)"/g, (_match, id) => `id="${scopeId}__${id}"`)
    .replace(/url\(#([^)]+)\)/g, (_match, id) => `url(#${scopeId}__${id})`)
    .replace(/href="#([^"]+)"/g, (_match, id) => `href="#${scopeId}__${id}"`)
    .replace(/xlink:href="#([^"]+)"/g, (_match, id) => `xlink:href="#${scopeId}__${id}"`);
}

export const AnalysisIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 24 24",
  "fill": "none"
},
  "<path d=\"M22 9V17C22 19.7614 19.7614 22 17 22H7C4.23858 22 2 19.7614 2 17V7C2 4.23858 4.23858 2 7 2H16\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/><circle cx=\"2\" cy=\"2\" r=\"2\" transform=\"matrix(-1 0 0 1 23 2)\" stroke=\"currentColor\" stroke-width=\"1.5\"/><path d=\"M7 14.75L10.5 10.75L13.5 13.25L17 9.25\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>"
);

export const ChartIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 24 24",
  "fill": "none"
},
  "<rect x=\"2\" y=\"2\" width=\"20\" height=\"20\" rx=\"5\" stroke=\"currentColor\" stroke-width=\"1.5\"/><path d=\"M8 17L8 14\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 17L12 7\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M16 17L16 10\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>"
);

export const ClockIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 32 32",
  "fill": "none"
},
  "<path d=\"M15.9946 29.3227C23.3558 29.3227 29.3232 23.3553 29.3232 15.9941C29.3232 8.63294 23.3558 2.66553 15.9946 2.66553C8.63343 2.66553 2.66602 8.63294 2.66602 15.9941C2.66602 23.3553 8.63343 29.3227 15.9946 29.3227Z\" stroke=\"currentColor\" stroke-width=\"2.66572\"/><path d=\"M15.9941 7.99707V15.9942L21.3256 18.6599\" stroke=\"currentColor\" stroke-width=\"2.66572\"/>"
);

export const CompanyIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 24 24",
  "fill": "none"
},
  "<path d=\"M4.53715 10.4713C4.80212 8.48412 6.49726 7 8.50207 7H15.4979C17.5027 7 19.1979 8.48412 19.4628 10.4713L20.3962 17.4713C20.7159 19.8693 18.8504 22 16.4313 22H7.56873C5.14958 22 3.2841 19.8693 3.60382 17.4713L4.53715 10.4713Z\" stroke=\"currentColor\" stroke-width=\"1.5\"/><path d=\"M16 9V6C16 3.79086 14.2091 2 12 2C9.79086 2 8 3.79086 8 6L8 9\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/>"
);

export const EmployeesIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 24 24",
  "fill": "none"
},
  "<circle cx=\"3.40426\" cy=\"3.40426\" r=\"3.40426\" transform=\"matrix(-1 0 0 1 15.6172 5)\" stroke=\"currentColor\" stroke-width=\"1.5\"/><path d=\"M6.25586 16.8594C6.25586 16.1272 6.71616 15.474 7.40572 15.2277C10.5146 14.1174 13.912 14.1174 17.0209 15.2277C17.7105 15.474 18.1708 16.1272 18.1708 16.8594V17.979C18.1708 18.9896 17.2757 19.7659 16.2753 19.6229L15.9417 19.5753C13.4687 19.222 10.958 19.222 8.48491 19.5753L8.15136 19.6229C7.15093 19.7659 6.25586 18.9896 6.25586 17.979V16.8594Z\" stroke=\"currentColor\" stroke-width=\"1.5\"/><path d=\"M17.3174 11.9026C18.7947 11.9026 19.9922 10.7051 19.9922 9.22787C19.9922 7.75064 18.7947 6.5531 17.3174 6.5531\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/><path d=\"M20.2471 18.0051L20.5092 18.0425C21.2952 18.1548 21.9985 17.5448 21.9985 16.7508V15.8711C21.9985 15.2958 21.6368 14.7826 21.095 14.5891C20.5546 14.3961 20.003 14.2458 19.4453 14.1382\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/><path d=\"M6.68258 11.9026C5.20535 11.9026 4.00781 10.7051 4.00781 9.22787C4.00781 7.75064 5.20535 6.5531 6.68258 6.5531\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/><path d=\"M3.75289 18.0051L3.49082 18.0425C2.70476 18.1548 2.0015 17.5448 2.0015 16.7508V15.8711C2.0015 15.2958 2.36316 14.7826 2.90496 14.5891C3.44541 14.3961 3.99696 14.2458 4.55469 14.1382\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/>"
);

export const EntryIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 24 24",
  "fill": "none"
},
  "<path d=\"M9 8L7 8C4.79086 8 3 9.79086 3 12L3 17C3 19.2091 4.79086 21 7 21L19 21C21.2091 21 23 19.2091 23 17L23 12C23 9.79086 21.2091 8 19 8L17 8\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/><path d=\"M10 13L12.2929 15.2929C12.6834 15.6834 13.3166 15.6834 13.7071 15.2929L16 13\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/><path d=\"M13 15L13 3\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/>"
);

export const FlagIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 17 22",
  "fill": "none"
},
  "<path d=\"M0.75 2.25C0.75 1.42157 1.42157 0.75 2.25 0.75H7.25C8.07843 0.75 8.75 1.42157 8.75 2.25V10.25C8.75 11.0784 8.07843 11.75 7.25 11.75H0.75V2.25Z\" stroke=\"currentColor\" stroke-width=\"1.5\"/><path d=\"M8.75 2.75H14.7862C15.6035 2.75 16.0757 3.6772 15.595 4.33817L13.6055 7.07366C13.0955 7.77496 13.0955 8.72504 13.6055 9.42634L15.595 12.1618C16.0757 12.8228 15.6035 13.75 14.7862 13.75H9.75C9.19772 13.75 8.75 13.3023 8.75 12.75V2.75Z\" stroke=\"currentColor\" stroke-width=\"1.5\"/><path d=\"M0.750001 20.75L0.75 2.75\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>"
);

export const HistoryIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 24 24",
  "fill": "none"
},
  "<path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M20.0378 2.7201C19.0731 1.75945 17.5097 1.76004 16.5457 2.72142L9.0903 10.1583C8.49401 10.753 8.14344 11.5492 8.10796 12.3891L8.00182 14.9018C7.9535 16.046 8.87116 16.9998 10.0203 16.9999L12.4924 17C13.4 17 14.2692 16.6349 14.9029 15.9874L22.2984 8.40804C23.2425 7.44344 23.2326 5.90152 22.2761 4.94907L20.0378 2.7201ZM17.4985 3.67018C17.9366 3.23319 18.6473 3.23293 19.0858 3.66958L21.3241 5.89856C21.7588 6.33149 21.7634 7.03236 21.3342 7.47082L19.8489 8.98837L16.0046 5.16008L17.4985 3.67018ZM15.0526 6.10956L10.043 11.1071C9.68526 11.4639 9.47492 11.9416 9.45363 12.4456L9.3475 14.9583C9.33139 15.3397 9.63728 15.6576 10.0203 15.6576L12.4924 15.6577C13.037 15.6578 13.5585 15.4387 13.9388 15.0502L18.9084 9.94931L15.0526 6.10956Z\" fill=\"currentColor\"/><path d=\"M21 13V17C21 19.7614 18.7614 22 16 22H8C5.23858 22 3 19.7614 3 17V9C3 6.23858 5.23858 4 8 4H12\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/>"
);

export const LockIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 20 20",
  "fill": "none"
},
  "<path d=\"M15.8333 9.1665H4.16667C3.24619 9.1665 2.5 9.9127 2.5 10.8332V16.6665C2.5 17.587 3.24619 18.3332 4.16667 18.3332H15.8333C16.7538 18.3332 17.5 17.587 17.5 16.6665V10.8332C17.5 9.9127 16.7538 9.1665 15.8333 9.1665Z\" stroke=\"currentColor\" stroke-width=\"1.66667\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M5.83398 9.1665V5.83317C5.83398 4.7281 6.27297 3.66829 7.05437 2.88689C7.83577 2.10549 8.89558 1.6665 10.0007 1.6665C11.1057 1.6665 12.1655 2.10549 12.9469 2.88689C13.7283 3.66829 14.1673 4.7281 14.1673 5.83317V9.1665\" stroke=\"currentColor\" stroke-width=\"1.66667\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>"
);

export const MailIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 20 20",
  "fill": "none"
},
  "<g clip-path=\"url(#clip0_4719_4853)\"><path d=\"M16.666 3.3335H3.33268C2.41221 3.3335 1.66602 4.07969 1.66602 5.00016V15.0002C1.66602 15.9206 2.41221 16.6668 3.33268 16.6668H16.666C17.5865 16.6668 18.3327 15.9206 18.3327 15.0002V5.00016C18.3327 4.07969 17.5865 3.3335 16.666 3.3335Z\" stroke=\"currentColor\" stroke-width=\"1.66667\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M18.3327 5.8335L10.8577 10.5835C10.6004 10.7447 10.3029 10.8302 9.99935 10.8302C9.69575 10.8302 9.39829 10.7447 9.14102 10.5835L1.66602 5.8335\" stroke=\"currentColor\" stroke-width=\"1.66667\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g><defs><clipPath id=\"clip0_4719_4853\"><rect width=\"20\" height=\"20\" fill=\"currentColor\"/></clipPath></defs>"
);

export const OutIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 24 24",
  "fill": "none"
},
  "<path d=\"M16.5 8.5L18.5 8.5C20.7091 8.5 22.5 10.2909 22.5 12.5L22.5 17.5C22.5 19.7091 20.7091 21.5 18.5 21.5L6.5 21.5C4.29086 21.5 2.5 19.7091 2.5 17.5L2.5 12.5C2.5 10.2909 4.29086 8.5 6.5 8.5L8.5 8.5\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/><path d=\"M15.5 5.5L13.2071 3.20711C12.8166 2.81658 12.1834 2.81658 11.7929 3.20711L9.5 5.5\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/><path d=\"M12.5 3.5L12.5 15.5\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/>"
);

export const PlusIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 22 22",
  "fill": "none"
},
  "<rect x=\"0.75\" y=\"0.75\" width=\"20\" height=\"20\" rx=\"5\" stroke=\"currentColor\" stroke-width=\"1.5\"/><path d=\"M7.75 10.75H13.75\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M10.75 7.75L10.75 13.75\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>"
);

export const RegisterInIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 24 24",
  "fill": "none"
},
  "<path d=\"M9 16V18C9 20.2091 10.7909 22 13 22H18C20.2091 22 22 20.2091 22 18V6C22 3.79086 20.2091 2 18 2H13C10.7909 2 9 3.79086 9 6V8\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/><path d=\"M14 15L16.2929 12.7071C16.6834 12.3166 16.6834 11.6834 16.2929 11.2929L14 9\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/><path d=\"M16 12L4 12\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/>"
);

export const RegisterOutIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 24 24",
  "fill": "none"
},
  "<path d=\"M16 16V18C16 20.2091 14.2091 22 12 22H7C4.79086 22 3 20.2091 3 18V6C3 3.79086 4.79086 2 7 2H12C14.2091 2 16 3.79086 16 6V8\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/><path d=\"M19 15L21.2929 12.7071C21.6834 12.3166 21.6834 11.6834 21.2929 11.2929L19 9\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/><path d=\"M21 12L9 12\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/>"
);

export const SearchIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 20 20",
  "fill": "none"
},
  "<path d=\"M9.16667 15.8333C12.8486 15.8333 15.8333 12.8486 15.8333 9.16667C15.8333 5.48477 12.8486 2.5 9.16667 2.5C5.48477 2.5 2.5 5.48477 2.5 9.16667C2.5 12.8486 5.48477 15.8333 9.16667 15.8333Z\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M17.5 17.5L13.875 13.875\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>"
);

export const TimerIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 24 24",
  "fill": "none"
},
  "<circle cx=\"12\" cy=\"12\" r=\"10\" stroke=\"currentColor\" stroke-width=\"1.5\"/><path d=\"M12 8V11.7324C12 11.8996 12.0836 12.0557 12.2226 12.1484L15 14\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\"/>"
);

export const UnionIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 19 18",
  "fill": "none"
},
  "<path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M10.5137 0.80666C11.5868 -0.268043 13.3275 -0.269078 14.4014 0.804707L16.8936 3.29689C17.958 4.36158 17.9686 6.08481 16.918 7.16311L7.68463 16.6367C6.97917 17.3605 6.01134 17.7686 5.00104 17.7686H2.24908C0.970104 17.7684 -0.0515485 16.7027 0.00201401 15.4238L0.120178 12.6143C0.159791 11.6754 0.550232 10.7849 1.21393 10.1201L10.5137 0.80666ZM17.5147 16.1953C17.9287 16.1953 18.2646 16.531 18.2647 16.9453C18.2647 17.3597 17.9288 17.6953 17.5147 17.6953H11.3936C10.9796 17.6953 10.6436 17.3597 10.6436 16.9453C10.6437 16.531 10.9796 16.1953 11.3936 16.1953H17.5147ZM2.27447 11.1817C1.87633 11.5805 1.64192 12.1145 1.61822 12.6778L1.50006 15.4863C1.48214 15.9126 1.82287 16.2683 2.24908 16.2686H5.00201C5.60797 16.2684 6.18824 16.023 6.61139 15.5889L13.1436 8.88576L8.85065 4.59377L2.27447 11.1817ZM13.3419 1.86623C12.8537 1.37807 12.0621 1.37868 11.5743 1.86721L9.91022 3.53225L14.1905 7.81154L15.8438 6.11623C16.3214 5.62618 16.3177 4.84244 15.834 4.35842L13.3419 1.86623Z\" fill=\"currentColor\"/>"
);

export const UpdateIcon = createIcon(
  {
  "xmlns": "http://www.w3.org/2000/svg",
  "viewBox": "0 0 24 24",
  "fill": "none"
},
  "<path\n    d=\"M12 6v6l4 2\"\n    stroke=\"currentColor\"\n    stroke-linecap=\"round\"\n    stroke-linejoin=\"round\"\n    stroke-width=\"2\"\n  /><path\n    d=\"M21 12a9 9 0 1 1-3.2-6.9\"\n    stroke=\"currentColor\"\n    stroke-linecap=\"round\"\n    stroke-width=\"2\"\n  /><path\n    d=\"M21 4v5h-5\"\n    stroke=\"currentColor\"\n    stroke-linecap=\"round\"\n    stroke-linejoin=\"round\"\n    stroke-width=\"2\"\n  />"
);

export const ICON_COMPONENTS = {
  "analysis": AnalysisIcon,
  "chart": ChartIcon,
  "clock": ClockIcon,
  "company": CompanyIcon,
  "employees": EmployeesIcon,
  "entry": EntryIcon,
  "flag": FlagIcon,
  "history": HistoryIcon,
  "lock": LockIcon,
  "mail": MailIcon,
  "out": OutIcon,
  "plus": PlusIcon,
  "registerIn": RegisterInIcon,
  "registerOut": RegisterOutIcon,
  "search": SearchIcon,
  "timer": TimerIcon,
  "union": UnionIcon,
  "update": UpdateIcon,
} satisfies Record<IconName, IconComponent>;
